### ISSUE TITLE
Can not compile Java RemotePrinter module

### ISSUE THREAD

**Issue by magdysalem2** [Azure/iot-edge#403] opened 2017-10-18 01:10 UTC
While compile RemotePrinter example I got the following weeoe
`azureuser@wmt-ubuntu:~/iot-edge/samples/java_sample/java_modules/RemotePrinter$ mvn clean install -U
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building sample-printer-module-remote 1.1.0
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/com/microsoft/azure/gateway/gateway-remote-module/1.0.0/gateway-remote-module-1.0.0.pom
[WARNING] The POM for com.microsoft.azure.gateway:gateway-remote-module:jar:1.0.0 is missing, no dependency information available
Downloading: http://repo.maven.apache.org/maven2/com/microsoft/azure/gateway/gateway-remote-module/1.0.0/gateway-remote-module-1.0.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.181s
[INFO] Finished at: Wed Oct 18 01:05:49 UTC 2017
[INFO] Final Memory: 10M/153M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project sample-printer-module-remote: Could not resolve dependencies for project com.microsoft.azure.gateway:sample-printer-module-remote:jar:1.1.0: Could not find artifact com.microsoft.azure.gateway:gateway-remote-module:jar:1.0.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
azureuser@wmt-ubuntu:~/iot-edge/samples/java_sample/java_modules/RemotePrinter$
`
It looks like the artifact gateway-remote-module and ateway-remote-module-1.0.0.jar are missing. I checked maven2 repo "http://repo.maven.apache.org/maven2" and I could not find them there. 

Any advice how we can get this code compile?

**Comment by damonbarry** [comment] 2017-11-28 18:10
I'm not able to reproduce this. Are you still seeing it? The output you provided says that Maven can't find the pom.xml file, but it's checked into the repo at `v1/proxy/gateway/java/gateway-remote-module/`.

**Comment by darobs** [comment] 2018-02-03 20:25
Closing this for lack of activity. Please reopen or open a new issue if this hasn't been resolved.

**Closed by darobs** 2018-02-03 20:25 UTC
Labels: question
