### ISSUE TITLE
Strange naming of properties in gateway configuration 

### ISSUE THREAD

**Issue by ddobric** [Azure/iot-edge#344] opened 2017-07-16 16:03 UTC
Hi all,

wouldn't be better change naming of properties "assembly.name" and "entry,type"?

NOW:

  "entrypoint": {
          "assembly.name": "IotEdgeGtw",
          "entry.type": "IotEdgeGtw.DebugModule"
        }

IT SHOULD BE:
  "entrypoint": {
          "assemblyName": "IotEdgeGtw",
          "entryType": "IotEdgeGtw.DebugModule"
        }

The reason for this propose, is that most JSON serializes cannot deal with "." in property names.

**Comment by avranju** [comment] 2017-07-17 01:44
This has been reported before. Could you please point to a serializer which has trouble with this? A small repro would be awesome.

**Comment by damonbarry** [comment] 2017-08-07 23:25
Duplicate of #304.

**Closed by damonbarry** 2017-08-07 23:25 UTC
