### ISSUE TITLE
417 - empty config

### ISSUE THREAD

**Issue by lucarv** [Azure/iot-edge#441] opened 2017-12-11 13:45 UTC
Tried to run edge on pi3, got this:
2017-12-11 13:43:47 [ERR] - Error refreshing edge agent configuration from twin.
Microsoft.Azure.Devices.Edge.Agent.Core.ConfigSources.ConfigEmptyException: This device has an empty configuration for the edge agent. Please set a deployment manifest.

clues?

**Comment by myagley** [comment] 2017-12-11 16:27
This is indicating that a deployment hasn't been targeted to this device and the configuration is empty. You can resolve by adding a deployment. This is described under the heading "Deploy a module" here:

[https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-simulate-device-Linux](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-simulate-device-Linux)

I hope this helps.

Thanks,
Mike

**Comment by lucarv** [comment] 2017-12-11 18:16
Thanks Mike

I guess I misunderstood things a bit. I thought it was possible to have a transparent GW, i.e a GW without any modules, i.e. the edgeHub would alwya sbe present. But if I got it right the edgeHub must be explicitely deployed or it gets deployed by adding another module (such as the tempSensor)?

**Comment by darobs** [comment] 2017-12-11 19:05
To get the edgeHub running, the device still needs a deployment, even if it has no modules. 

One way to do this in the Azure portal is to open the device details and select "SetModules" at the top. You can just select "Next" twice and then submit, and a deployment with no modules will be sent to the edge device.

We're still working on the user experience around this use case.

**Comment by myagley** [comment] 2018-04-19 19:48
This seems to be working as designed. Closing for now.

**Closed by myagley** 2018-04-19 19:48 UTC

**Comment by Jazmine9** [comment] 2018-07-16 21:25
I was working with IoT Edge and faced a similar issue. Try `docker ps -a` and delete all the edge containers and then restart IoT Edge. This helped in sorting out a 417 error. It is possible, that the edgeAgent module that you are running has some issues so ensure you have the correct edge Agent module. I had a preview edgeAgent instead of the correct edgeAgent image specified in the deployment manifest.
