### ISSUE TITLE
Modules directly attached with the devices gets over ridden by deployement

### ISSUE THREAD

**Issue by kkmsft** [Azure/iot-edge#433] opened 2017-12-01 18:01 UTC
Bug:
From the cloud portal its possible to attach a module to a device. If there is a deployment already for the device, then the edgeAgent deploys the container for the newly attached module first and after some time deletes it. The module also does not appear in the portal any more.

Expectation:
Either individual module attaching to the devices should be prevented or both deployment and individually attached module should be honored.

**Comment by varunpuranik** [comment] 2017-12-01 19:52
Thanks for the issue. This behavior is currently by design.
The deployment, or configuration system as we call it, doesn't take into account existing deployments on the device before applying the configuration. Also, all deployments have put semantics for now (so 2 deployments cannot be merged).
But this is good feedback and we will make a note of it for future improvements.

**Closed by varunpuranik** 2017-12-01 19:52 UTC
