### ISSUE TITLE
docker 17.11.0 doesn't seem to work by KeyNotFoundException

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/iot-edge#430] opened 2017-11-29 03:05 UTC
* [Deploy Azure IoT Edge on a simulated device in Linux - preview](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-simulate-device-linux)

I follow this instruction to create IoT Edge on a simulated device. I followed the instruction, however, I've got an error and I can't get connected to the IoT Hub.

```
2017-11-29 02:59:11 [ERR] - Error refreshing edge agent configuration from twin.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Microsoft.Azure.Devices.Client.DeviceClient.<>c__DisplayClass81_0.<ApplyTimeoutTwin>b__2(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Devices.Edge.Agent.IoTHub.EdgeAgentConnection.<RefreshTwinAsync>d__14.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs:line 87
2017-11-29 02:59:11 [WRN] - Skipped updating reported properties because no saved reported properties exist yet.
2017-11-29 02:59:11 [WRN] - Agent reconcile concluded with errors.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Microsoft.Azure.Devices.Edge.Agent.Core.Agent.<ReconcileAsync>d__9.MoveNext() in /opt/vsts/work/1/s/edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs:line 143
```

I noticed when I try docker-ce 17.11.0 on Ubuntu 16.04, it didn't work. However, when I downgrade the docker like 17.9 it works. Also, my friend said that he works but his environment is 17.10. Not 17.11. 

It might be related this issue. https://github.com/Azure/iot-edge/issues/418

**Comment by TsuyoshiUshio** [comment] 2017-11-29 17:19
I also noticed that even 17.09, sometimes I've got this error. However, I tried on 17.11 it always cause the error. I'm not sure it is totally depend on the version things. 
The solution of the error is to remove whole container images and re-run it. sometimes, it still cause the problem however, if you continue the workaround, it solves the problem for a couple of trying.

**Comment by avranju** [comment] 2017-11-29 20:11
This doesn't look like a problem that has to do with Docker or Ubuntu versions. It looks like a transient network issue. The fact that sometimes it works for you seems to support this case. I have not been able to reproduce this issue on my box.

When the error occurs do you see this happen repeatedly - i.e during every reconcile cycle for the agent?

**Comment by TsuyoshiUshio** [comment] 2017-11-30 02:31
Thank you for your help.  My environment is on Azure.  IoTHub, Virtual Machine (Ubuntu 16.04) on the same region. Not my local environment. I can share some VM which happen this issue to reproduce it if you like.

**Comment by avranju** [comment] 2017-11-30 03:19
I just setup a new Ubuntu 16.04 VM and installed Docker 17.11 on it and setup Azure IoT Edge and ran some modules and everything worked. I have not been able to reproduce this issue. I am wondering if the problem is on the service side. Are you trying this with an "edge" device in IoT Hub - i.e., did you create the device via the "IoT Edge" blade in the Azure portal?

**Comment by TsuyoshiUshio** [comment] 2017-11-30 03:48
I just follow this tutorial to create the environment. https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-simulate-device-linux

**Comment by avranju** [comment] 2017-12-21 00:09
We were eventually able to repro this issue on one VM! We have put out a new release today - `microsoft/azureiotedge-agent:1.0.0-preview017` - that has a fix for this issue. Do please feel free to give it a shot and see if this issue still occurs for you. You can run the `iotedgectl update` command to update the version of the Edge Agent running on your device.

**Comment by TsuyoshiUshio** [comment] 2017-12-26 01:04
Great! I'll give it try! Thank you so much indeed. BTW, What is the root cause?

**Comment by avranju** [comment] 2018-01-03 23:48
It appears to have been a transient network error that occurred sometimes in a specific cloud API call. The resolution was to introduce an exponential back-off based retry mechanism for this case and that seems to have fixed the problem.

**Comment by myagley** [comment] 2018-04-04 15:08
This has been fixed in the February release. Please reopen if you are still running into this issue. Thanks!

**Closed by myagley** 2018-04-04 15:08 UTC
