### ISSUE TITLE
[V1] C2(get_auto_ignore_args_function_, call)(C2(umock_c_strict_expected_,call), #call); called object is not a function or function pointer	

### ISSUE THREAD

**Issue by rohitjangra096** [Azure/iot-edge#523] opened 2018-02-21 07:29 UTC
Hey, 
can anyone please help to solve this issue, I am facing this problem when I compiling or build that code in ubuntu .

C2(get_auto_ignore_args_function_, call)(C2(umock_c_strict_expected_,call), #call);

#error ---->  called object is not a function or function pointer	umock_c.h

![screenshot from 2018-02-21 12 53 09](https://user-images.githubusercontent.com/36536096/36467765-27a4afec-16d8-11e8-9be8-c183d1ef5f03.png)

**Comment by avranju** [comment] 2018-02-28 01:28
Does this happen when you build via `tools/build.sh`?

**Comment by damonbarry** [comment] 2018-03-22 06:38
Closing since this appears to have gone cold. Please reopen in needed...

**Closed by damonbarry** 2018-03-22 06:38 UTC

**Comment by rohitjangra096** [comment] 2018-03-26 05:47
@avranju when I'm trying to build Microsoft Azure IoT Edge in eclipse then I'm facing this problem.
 In eclipse it is not compiling properly. so, can you please help to compile it in eclipse.

**Comment by rohitjangra096** [comment] 2018-03-26 05:55
@damonbarry  Please reopen this issue.

**Comment by avranju** [comment] 2018-03-26 17:01
Unfortunately, Eclipse is not something we use during our development and are not able to support with this. You may want to try reaching out on Eclipse forums. The Gateway SDK is a CMake project. I am not sure how well supported CMake is in Eclipse. The error you're pointing out seems to be happening in a C header which is part of the mocking framework we use for unit testing. The mocking library makes heavy use of C macros and its possible that this is a problem with the C parser that the Eclipse IDE is using. Again, your best bet is probably to ask on Eclipse forums or to build the code using the build scripts instead of Eclipse.

**Comment by damonbarry** [comment] 2018-03-26 17:41
@rohitjangra096 In addition to what @avranju said, if you can create an minimal, isolated program that reproduces the problem directly in the mocking framework (umock-c), you could open the issue in umock-c's [GitHub repo](https://github.com/Azure/umock-c/issues).

**Comment by rohitjangra096** [comment] 2018-03-27 06:52
Instead of Eclipse which IDE I can refer for Azure IoT Edge.

**Comment by rohitjangra096** [comment] 2018-03-27 06:56
One more thing I want to confirm that can we simply make Hello_world sample code by giving make command in linux terminal instead of using already generated binary file in build directory.

**Comment by damonbarry** [comment] 2018-03-27 16:14
@rohitjangra096 Yes you can just do:

```
cd v1/build/samples/hello_world
make
```

...and that will generate the binary file in the build directory. That's what our build script does to generate the binary.
