### ISSUE TITLE
IoT Edge is not available in a bunch of regions

### ISSUE THREAD

**Issue by faister** [Azure/iot-edge#421] opened 2017-11-17 04:03 UTC
As the subject implies, I have not been able to access IoT Edge after trying out in a number of regions which include US West, West 2, East, Central, and Australia East. What's missing?
![iothubnotavail](https://user-images.githubusercontent.com/8053228/32928881-7ddcef4e-cba8-11e7-8344-74752380473c.JPG)

**Comment by DBojsen** [comment] 2017-11-17 07:40
Hi @faister 

As per https://azure.microsoft.com/en-us/blog/azure-iot-edge-open-for-developers-to-build-for-the-intelligent-edge/ it is available in "US West Central, East Asia, North Europe, and West US, and the rest of the regions will be available shortly."

BR David

**Comment by yphuangms** [comment] 2017-11-20 13:00
Hi,

Since IoT Edge preview goes public, I've tried to create IoTHub service to try IoTEdge, and so far cannot enable IoT Edge supported on IoT Hub, all were rejected by the same error "IoT Edge is not available in "region" at this time. Please use IoT Hub in a different region". 

I've spent a lot of time try out each listed in the document, and none of them works - West Central US, East Asia, North Europe, West US.

![iotedge_regionerr_westcentralus](https://user-images.githubusercontent.com/14900924/33019495-9724bae2-ce35-11e7-8e63-39c046f78f2b.jpg)

![iotedge_regionerr_northeurope](https://user-images.githubusercontent.com/14900924/33019501-9eeec380-ce35-11e7-8a03-bf31676647d0.jpg)

![iotedge_regionerr_eastasia](https://user-images.githubusercontent.com/14900924/33019514-a6ac37ba-ce35-11e7-9234-81ea66b2a976.jpg)

Does any one success to enable IoT Edge on IoT Hub? Could you share which region you are using?

Thanks!

**Comment by myagley** [comment] 2017-11-21 01:18
This is caused by the additions made to the hosts file during the internal bug bash. Please remove the `main.iothub.ext.azure.com` line from your hosts file. This file is located at the following locations

```
Windows:   C:\Windows\System32\drivers\etc\hosts
Linix:     /etc/hosts
```
You will need Administrator/sudo to modify this file.

**Comment by myagley** [comment] 2017-11-21 01:19
Closing this, as it only affects Microsoft employees who participated in the bug bash.

**Closed by myagley** 2017-11-21 01:19 UTC
